markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : HackerHasid
production_url : http://www.hackerhasid.com
description: "Noah Blumenthal's thoughts and such"
disqus_shortname: hackerhasid
analytics: UA-43115922-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Noah Blumenthal
  github : hackerhasid
  twitter : hackerhasid
  email: noah@hackerhasid.com
